services:
#    louvre_ticket.example:
#        class: Louvre\TicketBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    louvre_ticket.agecalculator:
        class: Louvre\TicketBundle\AgeCalculator\LouvreAgeCalculator
